//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Tests = new HashSet<Test>();
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public int ContestId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Mark { get; set; }
    
        public virtual Contest Contest { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<Result> Results { get; set; }

        public override string ToString()
        {
            return this.Title;
        }
    }
}
